// <auto-generated />
using System;
using ECommerceApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceApi.Domain.Entities.Category", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
                b.Property<string>("ImageUrl").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<bool>("IsDeleted").HasColumnType("bit");
                b.Property<Guid?>("ParentId").HasColumnType("uniqueidentifier");
                b.Property<string>("Slug").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<int>("SortOrder").HasColumnType("int");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Slug").IsUnique();
                b.HasIndex("ParentId");
                b.ToTable("Categories");
            });

            modelBuilder.Entity("ECommerceApi.Domain.Entities.CategoryTranslation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("CategoryId").HasColumnType("uniqueidentifier");
                b.Property<string>("Description").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<string>("LanguageCode").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string>("MetaDescription").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("MetaTitle").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.HasIndex("CategoryId", "LanguageCode").IsUnique();
                b.ToTable("CategoryTranslations");
            });

            modelBuilder.Entity("ECommerceApi.Domain.Entities.PopularCategory", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("CategoryId").HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
                b.Property<int>("DisplayOrder").HasColumnType("int");
                b.Property<bool>("IsDeleted").HasColumnType("bit");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("CategoryId").IsUnique();
                b.ToTable("PopularCategories");
            });

            modelBuilder.Entity("ECommerceApi.Domain.Entities.SwiperSlide", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("CategoryId").HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
                b.Property<int>("DisplayOrder").HasColumnType("int");
                b.Property<string>("ImageUrl").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<bool>("IsDeleted").HasColumnType("bit");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("CategoryId");
                b.ToTable("SwiperSlides");
            });

            modelBuilder.Entity("ECommerceApi.Domain.Entities.SwiperSlideTranslation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("BigTitle").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("BottomText").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("HighlightedTitleBold").HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<string>("HighlightedTitleColor").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<string>("HighlightedTitleNormal").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<string>("LanguageCode").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<Guid>("SwiperSlideId").HasColumnType("uniqueidentifier");
                b.Property<string>("TopText").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.HasKey("Id");
                b.HasIndex("SwiperSlideId", "LanguageCode").IsUnique();
                b.ToTable("SwiperSlideTranslations");
            });
#pragma warning restore 612, 618
        }
    }
}
